# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: inlovewithcode
subtitle: Just another personal IT Blog or Journel of IT Learning.
email:
description: >- # this means to ignore newlines until "baseurl:"
  Personal Notes on Python, Oracel DB, Unix OS, Unix Shell Scripting, DB Schema Designing, Oracle Application Development, Python Data Scie - Pandas, Numpy, Matplotlib, Seaborn, Pandas Profiling, Tensorflow, Jupyter Notebook, Zepplin Notebook,  Apache Spark - PySpark, Scala, Dockers, Kubernetics, Elastic Search.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  inlovewithcode

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Adding pages site
include: ['_pages']

# Exclude showing folling pages
jekyll_admin:
  hidden_links:
    # - posts
    # - pages
    # - staticfiles
    # - datafiles
    # - configuration

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  # runnable script for local setup
  - utils
  # as name defines
  - junk
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
